export const login = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",

  VERIFY_REQUEST: "VERIFY_REQUEST",
  VERIFY_SUCCESS: "VERIFY_SUCCESS",
  VERIFY_FAILURE: "VERIFY_FAILURE",

  ADMIN_TOKEN_REQUEST: "ADMIN_TOKEN_REQUEST",
  ADMIN_TOKEN_SUCCESS: "ADMIN_TOKEN_SUCCESS",
  ADMIN_TOKEN_FAILURE: "ADMIN_TOKEN_FAILURE",
};

export const category = {
  GET_CATEGORY_REQUEST: "GET_CATEGORY_REQUEST",
  GET_CATEGORY_SUCCESS: "GET_CATEGORY_SUCCESS",
  GET_CATEGORY_FAILURE: "GET_CATEGORY_FAILURE",
};

export const merchant = {
  GET_MERCHANT_REQUEST: "GET_MERCHANT_REQUEST",
  GET_MERCHANT_SUCCESS: "GET_MERCHANT_SUCCESS",
  GET_MERCHANT_FAILURE: "GET_MERCHANT_FAILURE",
};
