export const login = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",

  VERIFY_REQUEST: "VERIFY_REQUEST",
  VERIFY_SUCCESS: "VERIFY_SUCCESS",
  VERIFY_FAILURE: "VERIFY_FAILURE",

  ADMIN_TOKEN_REQUEST: "ADMIN_TOKEN_REQUEST",
  ADMIN_TOKEN_SUCCESS: "ADMIN_TOKEN_SUCCESS",
  ADMIN_TOKEN_FAILURE: "ADMIN_TOKEN_FAILURE",
};

export const category = {
  GET_CATEGORY_REQUEST: "GET_CATEGORY_REQUEST",
  GET_CATEGORY_SUCCESS: "GET_CATEGORY_SUCCESS",
  GET_CATEGORY_FAILURE: "GET_CATEGORY_FAILURE",
};

export const merchant = {
  GET_MERCHANT_REQUEST: "GET_MERCHANT_REQUEST",
  GET_MERCHANT_SUCCESS: "GET_MERCHANT_SUCCESS",
  GET_MERCHANT_FAILURE: "GET_MERCHANT_FAILURE",
};

export const location = {
  GET_LOCATION_REQUEST: "GET_LOCATION_REQUEST",
  GET_LOCATION_SUCCESS: "GET_LOCATION_SUCCESS",
  GET_LOCATION_FAILURE: "GET_LOCATION_FAILURE",
};

export const product = {
  GET_PRODUCT_REQUEST: "GET_PRODUCT_REQUEST",
  GET_PRODUCT_SUCCESS: "GET_PRODUCT_SUCCESS",
  GET_PRODUCT_FAILURE: "GET_PRODUCT_FAILURE",

  ADD_CART_REQUEST: "ADD_CART_REQUEST",
  ADD_CART_SUCCESS: "ADD_CART_SUCCESS",
  ADD_CART_FAILURE: "ADD_CART_FAILURE",

  GET_CART_REQUEST: "GET_CART_REQUEST",
  GET_CART_SUCCESS: "GET_CART_SUCCESS",
  GET_CART_FAILURE: "GET_CART_FAILURE",

  UPDATE_CART_REQUEST: "UPDATE_CART_REQUEST",
  UPDATE_CART_SUCCESS: "UPDATE_CART_SUCCESS",
  UPDATE_CART_FAILURE: "UPDATE_CART_FAILURE",

  DELETE_CART_REQUEST: "DELETE_CART_REQUEST",
  DELETE_CART_SUCCESS: "DELETE_CART_SUCCESS",
  DELETE_CART_FAILURE: "DELETE_CART_FAILURE",

  SEARCH_PRODUCT_REQUEST: "SEARCH_PRODUCT_REQUEST",
  SEARCH_PRODUCT_SUCCESS: "SEARCH_PRODUCT_SUCCESS",
  SEARCH_PRODUCT_FAILURE: "SEARCH_PRODUCT_FAILURE",

  SEARCH_PRODUCT_DETAILS_REQUEST: "SEARCH_PRODUCT_DETAILS_REQUEST",
  SEARCH_PRODUCT_DETAILS_SUCCESS: "SEARCH_PRODUCT_DETAILS_SUCCESS",
  SEARCH_PRODUCT_DETAILS_FAILURE: "SEARCH_PRODUCT_DETAILS_FAILURE",
};

export const placeOrder = {
  GET_ADDRESS_REQUEST: "GET_ADDRESS_REQUEST",
  GET_ADDRESS_SUCCESS: "GET_ADDRESS_SUCCESS",
  GET_ADDRESS_FAILURE: "GET_ADDRESS_FAILURE",

  ADD_ADDRESS_REQUEST: "ADD_ADDRESS_REQUEST",
  ADD_ADDRESS_SUCCESS: "ADD_ADDRESS_SUCCESS",
  ADD_ADDRESS_FAILURE: "ADD_ADDRESS_FAILURE",

  EDIT_ADDRESS_REQUEST: "EDIT_ADDRESS_REQUEST",
  EDIT_ADDRESS_SUCCESS: "EDIT_ADDRESS_SUCCESS",
  EDIT_ADDRESS_FAILURE: "EDIT_ADDRESS_FAILURE",

  DELETE_ADDRESS_REQUEST: "DELETE_ADDRESS_REQUEST",
  DELETE_ADDRESS_SUCCESS: "DELETE_ADDRESS_SUCCESS",
  DELETE_ADDRESS_FAILURE: "DELETE_ADDRESS_FAILURE",
};

export const card = {
  GET_CARD_REQUEST: "GET_CARD_REQUEST",
  GET_CARD_SUCCESS: "GET_CARD_SUCCESS",
  GET_CARD_FAILURE: "GET_CARD_FAILURE",

  ADD_CARD_REQUEST: "ADD_CARD_REQUEST",
  ADD_CARD_SUCCESS: "ADD_CARD_SUCCESS",
  ADD_CARD_FAILURE: "ADD_CARD_FAILURE",

  EDIT_CARD_REQUEST: "EDIT_CARD_REQUEST",
  EDIT_CARD_SUCCESS: "EDIT_CARD_SUCCESS",
  EDIT_CARD_FAILURE: "EDIT_CARD_FAILURE",

  DELETE_CARD_REQUEST: "DELETE_CARD_REQUEST",
  DELETE_CARD_SUCCESS: "DELETE_CARD_SUCCESS",
  DELETE_CARD_FAILURE: "DELETE_CARD_FAILURE",
};

export const order = {
  GET_ORDER_REQUEST: "GET_ORDER_REQUEST",
  GET_ORDER_SUCCESS: "GET_ORDER_SUCCESS",
  GET_ORDER_FAILURE: "GET_ORDER_FAILURE",

  ADD_CARD_REQUEST: "ADD_CARD_REQUEST",
  ADD_CARD_SUCCESS: "ADD_CARD_SUCCESS",
  ADD_CARD_FAILURE: "ADD_CARD_FAILURE",

  EDIT_CARD_REQUEST: "EDIT_CARD_REQUEST",
  EDIT_CARD_SUCCESS: "EDIT_CARD_SUCCESS",
  EDIT_CARD_FAILURE: "EDIT_CARD_FAILURE",

  DELETE_CARD_REQUEST: "DELETE_CARD_REQUEST",
  DELETE_CARD_SUCCESS: "DELETE_CARD_SUCCESS",
  DELETE_CARD_FAILURE: "DELETE_CARD_FAILURE",
};

export const sendpackage = {
  GET_SEARCH_ADDRESS_REQUEST: "GET_SEARCH_ADDRESS_REQUEST",
  GET_SEARCH_ADDRESS_SUCCESS: "GET_SEARCH_ADDRESS_SUCCESS",
  GET_SEARCH_ADDRESS_FAILURE: "GET_SEARCH_ADDRESS_FAILURE"
};