export interface packageStateRequest {
    lat: any,
      long: any,
      isMarkerShown: boolean,
      city: string,
      cityerror: string,
      area: string,
      country: string,
      countryerror: string,
      state: string,
      stateerror: string,
      pincode: string,
      pincodeerror: string,
      addresserror: string,
      address: string,
      name: string,
      nameerror: string,
      addresstype:string,
      addresstypeerror: string,
      mobileerror: string,
      mobile: string,
      landmark: string,
      landmarkerror: string,
  }
  