export default {
  imagearray: [
    {
      src: "../assets/images/Groceries-Essentials.png",
      alt: "Groceries",
      name: "Groceries & Essentials",
    },
    {
      src: "../assets/images/Fruits-Vegetables.png",
      alt: "Fruits",
      name: "Fruits & Vegetables",
    },
    { src: "../assets/images/Meat-Fish.png", alt: "Meat", name: "Meat & Fish" },
    {
      src: "../assets/images/Food-Delivery.png",
      alt: "Food",
      name: "Food Delivery",
    },
    {
      src: "../assets/images/Medicines.png",
      alt: "Medicines",
      name: "Medicines",
    },
    {
      src: "../assets/images/Pet-Supplies.png",
      alt: "PetSupplies",
      name: "Pet Supplies",
    },
    {
      src: "../assets/images/Flowers-Gifts.png",
      alt: "Flowers",
      name: "Flowers & Gifts",
    },
  ],
  categoryColor: [
    { clr: "#E28424", bclr: "#E28424" },
    { clr: "#91C8E0", bclr: "#91C8E0" },
    { clr: "#606669", bclr: "#606669" },
    { clr: "#CC5144", bclr: "#CC5144" },
    { clr: "#CC5144", bclr: "#CC5144" },
    { clr: "#7ACAA6", bclr: "#7ACAA6" },
    { clr: "#412816", bclr: "#412816" },
    { clr: "#FF5463", bclr: "#FF5463" },
  ],

  apiUrl: "https://api-wildebeest-customer.techhoody.com/v1/api/",
  filepath: "https://api-wildebeest-admin.techhoody.com/",
  filemerchantpath: "https://api-wildebeest-merchant.techhoody.com/",
  fileuserpath: "https://api-wildebeest-customer.techhoody.com/",
  apiUrlAdmin: "https://api-wildebeest-admin.techhoody.com/v1/api/",
  apiUrlMerchant: "https://api-wildebeest-merchant.techhoody.com/v1/api/",
  home: "Get free online delivery for food,medicines,groceries and more | ...",
  about: "About",
  contact: "Contact-Us",
  findstore: "Groceries & Essentials",
  store: "Store",
  profile: "Profile",
  cart: "Cart",
  job: "Carrers",
  placeorder: "Place Order",
  searchcity: "Search City",
  trackorder: "Track Order",
  business: "Business",
  partners: "Partners",

  loginpage: {
    title: {
      login: "Signin",
    },
    state: {
      mobile: "",
      mobileerror: "",
      otp: "",
      otperror: "",
      isDisplay: false,
      disabled: false,
      isButton: false,
      disabled1: false,
      isButtonVerify: false,
      disabledInput: false,
    },
  },
  headerPage: {
    title: {},
    state: {
      isShow: false,
      count: 0,
    },
  },
  footerPage: {
    title: {},
    state: {
      isShow: false,
      footercitydata: [],
      footersocialdata: [],
    },
  },
  profilePage: {
    title: {},
    state: {
      mobile: "",
      addressarray: [],
      show: false,
      mobilephone: "",
      mobilephoneerror: "",
      addressid: "",
      addresstype: "1",
      orderdata: [],
      workdisabled: false,
      otherdisabled: false,
      homedisabled: false,

      updatemodel: false,
      update: false,
      firstname: "",
      firstnameerror: "",
      lastname: "",
      lastnameerror: "",
      useremail: "",
      useremailerror: "",
      file: "",
      filetrue: false,
      selectedFile: "",
      selectedFileerror: "",
      disable: false,
    },
  },
  categoryPage: {
    title: {},
    state: {
      categorydata: [],
      isLoading: true,
    },
  },
  searchCityPage: {
    title: {},
    state: {
      slugname: "",
      categorydata: [],
      isLoading: true,
      cityid: 3,
    },
  },
  findStorePage: {
    title: {},
    state: {
      count: "0",
      currentPage: "1",
      items_per_page: "4",
      upperPageBound: 6,
      lowerPageBound: 0,
      pageBound: 3,
      onItemSelect: "",
      switchSort: false,
      isStatus: false,
      slugname: "",
      location: "rajkot",
      merchantdata: [],
      locationData: [],
      isLoading: true,
      cityid: 3,
    },
  },
  bannerPage: {
    title: {},
    state: {
      lat: "",
      long: "",
      city: "",
      area: "",
      isSearch: false,
      location: "rajkot",
      locationData: [],
      cityid: "",
    },
  },
  storeItemPage: {
    title: {},
    state: {
      activeLink: 1,
      isShowCard: false,
      location: "rajkot",
      slugname: "",
      categorydata: [],
      productdata: [],
      cartarray: [],
      maindata: "",
      qty: 1,
      searchproductdata: [],
      searchproductdatadetails: [],
      isButton: false,
      loadingid: "",
      show: false,
      isLoading: true,
      loading:false
    },
  },
  cartPage: {
    title: {},
    state: {
      activeLink: "1",
      isShowCard: false,
      cartarray: [],
      isOpen: false,
    },
  },
  placeorderPage: {
    title: {},
    state: {
      checkedvalue: false,
      showSection: false,
      checkedpaymentvalue: false,
      checkedpaymentvaluewallets: false,
      checkedpaymentvaluecard: false,
      checkedpaymentvaluenetbanking: false,
      usermobile: "",
      addresstype: "1",
      paymenttype: 0,
      paytype: 0,
      banktype: 0,
      firstName: "",
      lastname: "",
      lat: "",
      long: "",
      city: "",
      cityerror: "",
      area: "",
      country: "",
      countryerror: "",
      state: "",
      stateerror: "",
      pincode: "",
      pincodeerror: "",
      addresserror: "",
      address: "",
      name: "",
      nameerror: "",
      addresstypeerror: "",
      mobileerror: "",
      mobile: "",
      landmark: "",
      landmarkerror: "",
      cartarray: [],
      addressarray: [],
      mainaddress: 0,
      addressid: 0,
      updateTrue: false,
      month: 1,
      year: 2020,
      cardnumber: "",
      cardnumbererror: "",
      cardholder: "",
      cardholdererror: "",
      cardtype: "",
      carddata: [],
      isCard: false,
      cvvid: 0,
      cvv: "",
      cvverror: "",
      cardid: 0,
      cardUpdateTrue: false,
      cvvdesc: false,
      workdisabled: false,
      otherdisabled: false,
      homedisabled: false,

      montherror: "",
      changewallet: 0,
      amount: 0,
      amounterror: "",
      codename: "",
      upiTrue: false,
      cardTrue: false,
      walletTrue: false,
      netbankingTrue: false,
      freecharge: false,
      olamoney: false,
      payzapp: false,
      AMEX: "",
      BAJAJ: "",
      DICL: "",
      JCB: "",
      MAES: "",
      MC: "",
      RUPAY: "",
      VISA: "",
      bankarray: [],
      walletnumber: 0,
      walletnumbererror: "",
      coupondetails: [],
      openModel: false,
      couponShow: false,
      couponid: 0,
      couponapplieddata: "",
      discount: "0",
      totalpay: "0",
      couponerror: "",
      isShowApplied: false,
    },
    bankarray: [
      { title: "Airtel Payments Bank", value: "6" },
      { title: "Allahabad Bank", value: "7" },
      { title: "Andhra Bank", value: "8" },
      { title: "AU Small Finance Bank", value: "9" },
      { title: "Bandhan Bank", value: "10" },
      { title: "Bassien Catholic Co-Operative Bank", value: "11" },
      { title: "BNP Paribas", value: "12" },
      { title: "Bank of Bahrain and Kuwait", value: "13" },
      { title: "Bank of Baroda", value: "14" },
      { title: "Bank of Baroda Corporate", value: "15" },
      { title: "Bank of Baroda Retail", value: "16" },
      { title: "Bank of India", value: "17" },
      { title: "Bank of Maharashtra", value: "18" },
      { title: "Canara Bank", value: "19" },
      { title: "Catholic Syrian Bank", value: "20" },
      { title: "Central Bank", value: "21" },
      { title: "City Union Bank", value: "22" },
      { title: "Corporation Bank", value: "23" },
      { title: "Cosmos Co-op Bank", value: "24" },
      { title: "digibank by DBS", value: "25" },
      { title: "DCB BANK LTD", value: "26" },
      { title: "Dena Bank", value: "27" },
      { title: "Deutsche Bank", value: "28" },
      { title: "Dhanalakshmi Bank", value: "29" },
      { title: "Federal Bank", value: "30" },
      { title: "IDBI Bank", value: "31" },
      { title: "IDFC FIRST Bank", value: "32" },
      { title: "Indian Bank", value: "33" },
      { title: "IndusInd Bank", value: "34" },
      { title: "Indian Overseas Bank", value: "35" },
      { title: "JANATA SAHAKARI BANK LTD PUNE", value: "36" },
      { title: "J&amp;K Bank", value: "37" },
      { title: "Karnataka Bank", value: "38" },
      { title: "Karur Vysya Bank", value: "39" },
      { title: "Lakshmi Vilas Bank - Retail", value: "40" },
      { title: "Oriental Bank of Commerce", value: "41" },
      { title: "Punjab National Bank", value: "42" },
      { title: "Punjab National Bank Corporate", value: "43" },
      { title: "Punjab &amp; Sind Bank", value: "44" },
      { title: "Punjab &amp; Maharashtra Co-op Bank", value: "45" },
      { title: "RBL Bank – Net Banking", value: "46" },
      { title: "RBS", value: "47" },
      { title: "Saraswat Co-op Bank", value: "48" },
      { title: "Shamrao Vithal Co-op Bank", value: "49" },
      { title: "Shivalik Mercantile Co-op Bank", value: "50" },
      { title: "The South Indian Bank", value: "51" },
      { title: "Standard Chartered Bank", value: "52" },
      { title: "Syndicate Bank", value: "53" },
      { title: "Tamilnad Mercantile Bank Limited", value: "54" },
      { title: "Tamil Nadu Merchantile Bank", value: "55" },
      { title: "TNSC Bank", value: "56" },
      { title: "UCO Bank", value: "57" },
      { title: "Union Bank of India", value: "58" },
      { title: "United Bank of India", value: "59" },
      { title: "Vijaya Bank", value: "60" },
      { title: "Yes Bank", value: "61" },
      { title: "The Zoroastrian Co-Operative Bank", value: "62" },
    ],
    montharray: [
      { title: "01", value: "1" },
      { title: "02", value: "2" },
      { title: "03", value: "3" },
      { title: "04", value: "4" },
      { title: "05", value: "5" },
      { title: "06", value: "6" },
      { title: "07", value: "7" },
      { title: "08", value: "8" },
      { title: "09", value: "9" },
      { title: "10", value: "10" },
      { title: "11", value: "11" },
      { title: "12", value: "12" },
    ],
    yeararray: [
      { title: "20", value: "2020" },
      { title: "21", value: "2021" },
      { title: "22", value: "2022" },
      { title: "23", value: "2023" },
      { title: "24", value: "2024" },
      { title: "25", value: "2025" },
      { title: "26", value: "2026" },
      { title: "27", value: "2027" },
      { title: "28", value: "2028" },
      { title: "29", value: "2029" },
      { title: "30", value: "2030" },
      { title: "31", value: "2031" },
      { title: "32", value: "2032" },
      { title: "33", value: "2033" },
      { title: "34", value: "2034" },
      { title: "35", value: "2035" },
      { title: "36", value: "2036" },
      { title: "37", value: "2037" },
      { title: "38", value: "2038" },
      { title: "39", value: "2039" },
      { title: "40", value: "2040" },
      { title: "41", value: "2041" },
      { title: "42", value: "2042" },
      { title: "43", value: "2043" },
      { title: "44", value: "2044" },
      { title: "45", value: "2045" },
      { title: "46", value: "2046" },
      { title: "47", value: "2047" },
      { title: "48", value: "2048" },
      { title: "49", value: "2049" },
      { title: "50", value: "2050" },
    ],
  },
  packagesPage: {
    title: {},
    state: {
      lat: 22.2856,
      long: 70.7561,
      lat1: 22.2856,
      long1: 70.7561,
      isMarkerShown: false,
      city: "",
      cityerror: "",
      area: "",
      country: "",
      countryerror: "",
      state: "",
      stateerror: "",
      pincode: "",
      pincodeerror: "",
      addresserror: "",
      address: "",
      name: "",
      nameerror: "",
      addresstype: "1",
      addressdroptype: "1",
      addresstypeerror: "",
      mobileerror: "",
      mobile: "",
      landmark: "",
      landmarkerror: "",
      addressarray: [],
      show: false,
      showMap: false,
      selectblock: false,
      username: "",
      usermobile: "",
      flat: "",
      reach: "",
      flaterror: "",
      reacherror: "",
      continueBlock: false,

      show1: false,
      showMap1: false,
      selectblock1: false,
      selectedaddress: "",
      selectedaddressdrop: "",
      username1: "",
      usermobile1: "",
      flat1: "",
      reach1: "",
      flat1error: "",
      reach1error: "",
      name1: "",
      mobile1: "",
      name1error: "",
      mobile1error: "",
      homeerror: "",
      workerror: "",
      home1error: "",
      work1error: "",
      searchaddress: [],
      searchSection: false,
      cartarray: [],
      clearcart: false,
      displaydesc: false,
      addressmaintype: "",
      addressmaintype1: "",
    },
  },

  servicePage: {
    title: {},
    state: {
      mobile: "",
      mobileerror: "",
      hide: false,
    },
  },
};
