export interface placeorderStateRequest {
    checkedvalue: boolean,
    showSection: boolean,
    checkedpaymentvalue: boolean,
    checkedpaymentvaluewallets: boolean,
    checkedpaymentvaluecard: boolean,
    checkedpaymentvaluenetbanking: boolean,
    usermobile:string,
    addresstype:any,
    paymenttype:any,
    paytype:any,
    banktype:any,
    firstName:string,
    lastname:string,
    lat:any,
    long:any,
    city:string,
    cityerror:string,
    area:any,
    country:any,
    state:any,
    pincode:any,
    address:any,
    countryerror:string,
    stateerror: string,
    pincodeerror: string,
    addresserror:string,
    name:any,
    nameerror: string,
    addresstypeerror:string,
    mobileerror: string,
    mobile:any,
    landmark:any,
    landmarkerror:string,
    cartarray:any,
    addressarray:any
}