export interface profileStateRequest {
    mobile:string,
    addressarray:any,
    show:boolean,
    mobilephone:string,
    mobilephoneerror:string,
    addressid:string,
    addresstype:string,
    orderdata:any,
    workdisabled:boolean,
    otherdisabled:boolean,
    homedisabled:boolean,

    updatemodel: boolean,
    update: boolean,
    firstname: string,
    firstnameerror: string,
    lastname: string,
    lastnameerror: string,
    useremail: string,
    useremailerror: string,
    file: string,
    filetrue: boolean,
    selectedFile: string,
    selectedFileerror: string,
    disable: boolean,
}